# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# https://docs.readthedocs.com/platform/stable/config-file/v2.html#build
build:
  os: ubuntu-26.04
  tools:
    python: "3.13"
  apt_packages:
    - cmake
    - doxygen
    - graphviz
  jobs:
    build:
      html:
        - mkdir -p $READTHEDOCS_OUTPUT
        - cmake -S . -B build -DDOXYGEN_OUTPUT_DIRECTORY=$READTHEDOCS_OUTPUT -DDOC_FOR_USER=YES
        - cmake --build build --target doxygen
        - ls -lrta $READTHEDOCS_OUTPUT

submodules:
  include: all
