# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# https://docs.readthedocs.com/platform/stable/config-file/v2.html#build
build:
  os: ubuntu-26.04
  tools:
    python: "3.13"
  apt_packages:
    - cmake
    - doxygen
    - graphviz
  jobs:
    build:
      html:
        - cmake -S . -B build
        - cmake --build build --target doxygen
        - mkdir -p $READTHEDOCS_OUTPUT/build/doc/html
        - cp -rf build/doc/html $READTHEDOCS_OUTPUT
